crypto_tax_checker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.documentation import include_docs_urls, get_schemajs_view

schemajs_view = get_schemajs_view(title="API")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('users/', include('apps.users.urls')),
    path('subscriptions/', include('apps.subscriptions.urls')),
    path('', include('apps.web.urls')),
    path('web', include('apps.web.urls')),
    path('pegasus/', include('pegasus.apps.examples.urls')),
    path('pegasus/employees/', include('pegasus.apps.employees.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    # API docs
    # these are needed for schema.js
    path('docs/', include_docs_urls(title='API Docs')),
    path('schemajs/', schemajs_view, name='api_schemajs'),
    # djstripe urls - for webhooks
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
    # Adding my portfolio urls
    path('portfolio/', include('apps.portfolio.urls', namespace="portfolio")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pegasus/apps/employees/urls.py
from django.urls import path
from django.views.generic import TemplateView
from rest_framework import routers

from . import views


app_name = 'pegasus_employees'

urlpatterns = [
    path('objects/', TemplateView.as_view(template_name='pegasus/employees/object_lifecycle_home.html',
                                          extra_context={'active_tab': 'object_lifecycle'}),
         name='object_lifecycle_home', ),
    path('objects/django/', views.employee_list, name='django_object_lifecycle'),
    path('objects/django/new/', views.new_employee, name='django_new_employee'),
    path('objects/django/edit/<int:employee_id>/', views.edit_employee, name='django_edit_employee'),
    path('objects/django/delete/<int:employee_id>/', views.delete_employee, name='django_delete_employee'),

    path('objects/htmx/', views.employee_list_htmx, name='htmx_object_lifecycle'),
    path('objects/htmx/new/', views.new_employee_row_htmx, name='htmx_new_employee'),
    path('objects/htmx/empty/', views.empty_htmx, name='htmx_empty'),

    path('objects/htmx/edit/<int:employee_id>/', views.edit_employee_row_htmx, name='htmx_edit_employee'),
    path('objects/htmx/get/<int:employee_id>/', views.get_employee_row_htmx, name='htmx_get_employee'),
    path('objects/htmx/delete/<int:employee_id>/', views.delete_employee_htmx, name='htmx_delete_employee'),

    path('objects/react/', views.ReactObjectLifecycleView.as_view(), name='react_object_lifecycle'),
    path('objects/react/<path:path>', views.ReactObjectLifecycleView.as_view(), name='react_object_lifecycle_w_path'),
    path('objects/vue/', views.VueObjectLifecycleView.as_view(), name='vue_object_lifecycle'),
    path('charts/', views.ChartsView.as_view(), name='charts'),

    path('api/employee-data/', views.EmployeeDataAPIView.as_view(), name='employee_data'),
]


# drf config
router = routers.DefaultRouter()
router.register('api/employees', views.EmployeeViewSet)

urlpatterns += router.urls

pegasus/apps/examples/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from . import views


app_name = 'pegasus_examples'

urlpatterns = [
    path('', views.ExamplesHomeView.as_view(), name='examples_home'),
    path('payments', views.PaymentView.as_view(), name='payments'),
    # payments via elements
    path('payments/create_payment_intent/', views.create_payment_intent, name='create_payment_intent'),
    path('payments/create/', views.accept_payment, name='accept_payment'),
    path('payments/confirm/<slug:payment_id>/', views.payment_confirm, name='payment_confirm'),
    # payments via checkout
    path('payments/create-checkout-session/', views.create_checkout_session, name='create_checkout_session'),
    path('payments/checkout-success/', views.checkout_success, name='checkout_success'),
    path('payments/checkout-canceled/', views.checkout_canceled, name='checkout_canceled'),

    path('landing_page/', TemplateView.as_view(template_name='pegasus/examples/example_landing_page.html'),
         name='landing_page'),
    path('pricing_page/', TemplateView.as_view(template_name='pegasus/examples/example_pricing_page.html'),
         name='pricing_page'),

    # these are experimental examples that aren't currently exposed in the UI.
    path('alpine/', TemplateView.as_view(template_name='pegasus/examples/alpine_demo.html'), name='alpine_demo'),
    path('forms/', views.ExampleFormView.as_view(), name='form_demo'),

    # tasks
    path('tasks/', views.TasksView.as_view(), name='tasks'),
    path('tasks/api/', views.tasks_api, name='tasks_api'),
]

pegasus/apps/employees/models.py
from django.conf import settings
from django.db import models

from apps.utils.models import BaseModel


class Employee(BaseModel):
    DEPARTMENT_CHOICES = (
        ('hr', 'Human Resources'),
        ('finance', 'Finance'),
        ('engineering', 'Engineering'),
        ('marketing', 'Marketing'),
        ('sales', 'Sales'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='employees')
    name = models.CharField(max_length=100, help_text="Your employee's name.")
    department = models.CharField(max_length=20, choices=DEPARTMENT_CHOICES,
                                  help_text='What department your employee belongs to.')
    salary = models.PositiveIntegerField(help_text="Your employee's annual salary.")

    def __str__(self):
        return self.name

pegasus/apps/employees/forms.py
from django import forms

from .models import Employee


class EmployeeForm(forms.ModelForm):

    class Meta:
        model = Employee
        fields = ('name', 'department', 'salary')

pegasus/apps/employees/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Avg, Sum, Count
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.templatetags.static import static
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST, require_http_methods
from django.views.generic import TemplateView
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.views import APIView

from .forms import EmployeeForm
from .models import Employee
from .serializers import EmployeeSerializer


@login_required
def employee_list(request):
    return render(request, 'pegasus/employees/list_employees.html', {
        'active_tab': 'object_lifecycle',
        'employees': Employee.objects.filter(user=request.user)
    })


@login_required
def new_employee(request):
    return _add_edit_employee(request)


@login_required
def edit_employee(request, employee_id):
    # don't forget to filter by user, else you'll allow people to edit other people's employees!
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    return _add_edit_employee(request, employee)


def _add_edit_employee(request, employee: Employee = None):
    if employee:
        assert employee.user == request.user
    if request.method == 'POST':
        form = EmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            employee = form.save(commit=False)
            employee.user = request.user
            employee.save()
            return HttpResponseRedirect(reverse('pegasus_employees:django_object_lifecycle'))
    else:
        form = EmployeeForm(instance=employee)

    return render(request, 'pegasus/employees/edit_employee.html', {
        'active_tab': 'object_lifecycle',
        'employee': employee,
        'form': form,
    })


@require_POST
@login_required
def delete_employee(request, employee_id):
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    employee.delete()
    return HttpResponseRedirect(reverse('pegasus_employees:django_object_lifecycle'))


@login_required
def employee_list_htmx(request):
    return render(request, 'pegasus/employees/htmx_object_lifecycle.html', {
        'active_tab': 'object_lifecycle',
        'employees': Employee.objects.filter(user=request.user)
    })


@login_required
def new_employee_row_htmx(request):
    return _add_edit_employee_htmx(request)


@login_required
def edit_employee_row_htmx(request, employee_id):
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    return _add_edit_employee_htmx(request, employee)


def _add_edit_employee_htmx(request, employee=None):
    if request.method == 'POST':
        form = EmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            employee = form.save(commit=False)
            employee.user = request.user
            employee.save()
            return HttpResponseRedirect(reverse('pegasus_employees:htmx_get_employee', args=[employee.id]))
    else:
        form = EmployeeForm(instance=employee)

    return render(request, 'pegasus/employees/htmx/edit_employee_row.html', {
        'employee': employee,
        'form': form,
    })


def empty_htmx(request):
    return HttpResponse('')


@login_required
def get_employee_row_htmx(request, employee_id):
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    return render(request, 'pegasus/employees/htmx/employee_row.html', {
        'employee': employee,
    })


@require_http_methods(['DELETE'])
@login_required
def delete_employee_htmx(request, employee_id):
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    employee.delete()
    return HttpResponse('')


@method_decorator(login_required, name='dispatch')
class ObjectLifecycleView(TemplateView):
    def get_context_data(self, **kwargs):
        return {
            'department_choices': [{
                'id': c[0],
                'name': c[1]
            } for c in Employee.DEPARTMENT_CHOICES],
        }


class ReactObjectLifecycleView(ObjectLifecycleView):
    template_name = 'pegasus/employees/react_object_lifecycle.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'framework_url': 'https://reactjs.org/',
            'framework_name': 'React',
            'framework_icon': static('images/pegasus/react-icon.png'),
            'active_tab': 'object_lifecycle',
            'url_base': reverse('pegasus_employees:react_object_lifecycle'),
        })
        return context


class VueObjectLifecycleView(ObjectLifecycleView):
    template_name = 'pegasus/employees/vue_object_lifecycle.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'framework_url': 'https://vuejs.org/',
            'framework_name': 'Vue.js',
            'framework_icon': static('images/pegasus/vue-icon.png'),
            'active_tab': 'object_lifecycle',
            'url_base': reverse('pegasus_employees:vue_object_lifecycle'),
        })
        return context


@method_decorator(login_required, name='dispatch')
class ChartsView(TemplateView):
    template_name = 'pegasus/employees/charts.html'

    def get_context_data(self, **kwargs):
        return {
            'active_tab': 'charts',
        }


class EmployeeDataAPIView(APIView):

    def get(self, request):
        user = request.user
        data = user.employees.values('department').annotate(
            average_salary=Avg('salary'),
            total_cost=Sum('salary'),
            number_employees=Count('pk'),
        )
        # data will look something like this:
        # [
        #     {'total_cost': 132000, 'number_employees': 2, 'average_salary': 66000.0, 'department': 'hr'},
        #     {'total_cost': 60000, 'number_employees': 1, 'average_salary': 60000.0, 'department': 'marketing'}
        # ]
        total_costs = [
            [row['department'], row['total_cost']] for row in data
        ]
        average_salaries = [
            [row['department'], row['average_salary']] for row in data
        ]
        headcounts = [
            [row['department'], row['number_employees']] for row in data
        ]
        return Response({
            'total_costs': total_costs,
            'average_salaries': average_salaries,
            'headcounts': headcounts,
        })


class EmployeeViewSet(viewsets.ModelViewSet):
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer

    def get_queryset(self):
        # filter queryset based on logged in user
        return self.request.user.employees.all()

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

pegasus/apps/examples/views/payments_views.py
import stripe
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView

from apps.web.meta import absolute_url
from ..models import Payment

EXPECTED_PAYMENT_AMOUNT = 2500  # in cents


@method_decorator(login_required, name='dispatch')
class PaymentView(TemplateView):
    template_name = 'pegasus/examples/payments/payments.html'

    def get_context_data(self, **kwargs):
        return {
            'stripe_key': settings.STRIPE_TEST_PUBLIC_KEY,
            'payments': self.request.user.pegasus_payments.all(),
            'amount': EXPECTED_PAYMENT_AMOUNT,
            'active_tab': 'payments',
        }


@login_required
@require_POST
def create_payment_intent(request):
    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    intent = stripe.PaymentIntent.create(
        amount=EXPECTED_PAYMENT_AMOUNT,
        currency='usd',
        description=f'A Demo Payment',
    )
    return JsonResponse({
        'client_secret': intent['client_secret'],
    })


@login_required
def payment_confirm(request, payment_id):
    """
    Confirmation page after making a payment.
    """
    payment = get_object_or_404(Payment, user=request.user, id=payment_id)
    return render(request, 'pegasus/examples/payments/payment_confirm.html', {
        'payment': payment,
        'active_tab': 'payments',
    })


@login_required
@require_POST
def accept_payment(request):
    """
    Accept a payment with a token from Stripe
    """
    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    name = request.POST['name']
    try:
        payment_intent_id = request.POST['paymentIntent']
    except KeyError:
        messages.error(request, 'Problem processing that payment. Please try again!')
        return HttpResponseRedirect(reverse('pegasus_examples:payments'))
    payment_intent = stripe.PaymentIntent.retrieve(payment_intent_id)
    if payment_intent.status != 'succeeded':
        raise Exception(f'Unexpected payment intent status: {payment_intent.status}')

    amount = payment_intent['amount']
    if amount != EXPECTED_PAYMENT_AMOUNT:
        raise ValueError(f'Unexpected payment amount {payment_intent["amount"]}')

    charge = payment_intent['charges']['data'][0]

    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    user = request.user
    payment = Payment.objects.create(
        charge_id=charge.id,
        amount=charge.amount,
        name=name,
        user=user,
    )
    return HttpResponseRedirect(reverse('pegasus_examples:payment_confirm', args=[payment.payment_id]))


@require_POST
@login_required
def create_checkout_session(request):
    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    success_url = absolute_url(reverse('pegasus_examples:checkout_success'))
    cancel_url = absolute_url(reverse('pegasus_examples:checkout_canceled'))
    checkout_session = stripe.checkout.Session.create(
        success_url=success_url + '?session_id={CHECKOUT_SESSION_ID}',
        cancel_url=cancel_url,
        customer_email=request.user.email,
        payment_method_types=['card'],
        mode='payment',
        line_items=[{
            'price_data': {
                'currency': 'usd',
                'product_data': {
                    'name': 'Sample Payment',
                },
                'unit_amount': 2500,
            },
            'quantity': 1,
        }],
        allow_promotion_codes=True,
    )
    return HttpResponseRedirect(checkout_session.url)


@login_required
def checkout_success(request):
    session_id = request.GET.get('session_id')
    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    session = stripe.checkout.Session.retrieve(session_id, expand=['payment_intent'])
    assert len(session.payment_intent.charges.data) == 1
    charge_id = session.payment_intent.charges.data[0].id
    payment = Payment.objects.create(
        charge_id=charge_id,
        amount=session.amount_total,
        name='Payment from Checkout',
        user=request.user,
    )
    return HttpResponseRedirect(reverse('pegasus_examples:payment_confirm', args=[payment.payment_id]))


@login_required
def checkout_canceled(request):
    messages.info(request, 'Your payment was canceled.')
    return HttpResponseRedirect(reverse('pegasus_examples:payments'))

templates/pegasus/employees/charts.html
{% extends "pegasus/examples/examples_base.html" %}
{% block page_head %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/c3/0.7.1/c3.min.css">
{% endblock %}
{% load static %}
{% block app %}
  <section class="app-card">
    <h1 class="pg-title">Charts Example</h1>
    <div class="content">
      <p>
        A basic end-to-end implementation of charts for your application,
        based on data from the <a href="{% url 'pegasus_employees:object_lifecycle_home' %}">Employee App</a>.
      </p>
    </div>
    <div class="pg-columns">
      <div class="pg-column">
        <div class="pg-subtitle pg-text-centered">Budget by Department</div>
        <div id="department-spend-chart"></div>
      </div>
      <div class="pg-column">
        <div class="pg-subtitle pg-text-centered">Average Salary by Department</div>
        <div id="department-salaries-chart"></div>
      </div>
    </div>
  </section>
  <div id="crud-home"></div>
{% endblock %}
{% block page_js %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.7.1/c3.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/5.9.2/d3.min.js"></script>
  <script src="{% static 'rest_framework/js/coreapi-0.1.1.js' %}"></script>
  <script src="{% url 'api_schemajs' %}"></script>
  <script src="{% static 'js/pegasus-bundle.js' %}"></script>
  <script src="{% static 'js/app-bundle.js' %}"></script>
  <script>
    const objectUrl = '{% url "pegasus_employees:react_object_lifecycle" %}';
    const Charts = SiteJS.pegasus.Charts;
    const client = SiteJS.app.Api.getApiClient();

    document.addEventListener('DOMContentLoaded', () => {
      client.action(window.schema, Charts.getListEmployeesAction()).then(function (result) {
        if (result.headcounts.length === 0) {
          let noData = '<p class="has-text-centered">No data! First <a href="' + objectUrl + '">create some employees</a>.</p>';
          document.getElementById('department-spend-chart').innerHTML = noData;
          document.getElementById('department-salaries-chart').innerHTML = noData;
        } else {
          Charts.renderChart('pie', '#department-spend-chart', result['total_costs']);
          Charts.renderChart('bar', '#department-salaries-chart', result['average_salaries']);
        }
      });
    });
  </script>
{% endblock %}

templates/pegasus/employees/django_object_lifecycle_base.html
{% extends "pegasus/examples/examples_base.html" %}
{% load static %}
{% block app %}
  <nav aria-label="breadcrumbs">
    <ol class="pg-breadcrumbs">
      <li class=""><a href="{% url 'pegasus_employees:object_lifecycle_home' %}">Employee Lifecycle App</a></li>
      <li class="pg-breadcrumb-active" aria-current="page">Django Forms</li>
    </ol>
  </nav>
  <section class="app-card">
    <div class="pg-columns">
      <div class="pg-column-one-quarter pg-text-centered">
        <img class="img-fluid" alt="Django" src="{% static 'images/pegasus/django-icon.png' %}" style="max-height: 160px;"/>
      </div>
      <div class="pg-column">
        <h1 class="pg-title">Django Object Lifecycle Demo</h1>
        <h2 class="pg-subtitle">
          An interactive data model and UI example.
        </h2>
        <div class="content">
          <p>
            This is an interactive data model and UI example using Django templates and forms.
            It demonstrates performing simple create, read, update and delete (CRUD) operations on an example
            "Employee" data model.
          </p>
        </div>
      </div>
    </div>
  </section>
  {% block django_app %}{% endblock %}
{% endblock %}

templates/pegasus/employees/edit_employee.html
{% extends "pegasus/employees/django_object_lifecycle_base.html" %}
{% load form_tags %}
{% block django_app %}
  <div class="app-card">
    <h2 class="pg-subtitle">Employee Details</h2>
    <form method="post">
      {% csrf_token %}
      {% render_form_fields form %}
      <input type="submit" value="Save Employee" class="pg-button-secondary">
    </form>
  </div>
{% endblock %}

templates/pegasus/employees/htmx_object_lifecycle.html
{% extends "pegasus/examples/examples_base.html" %}
{% load static %}
{% block page_head %}
  <script src="https://unpkg.com/htmx.org@1.5.0"></script>
  <style>
    /* make an editable grid that looks like a table: https://stackoverflow.com/a/15600151/8207 */
    div.table
    {
        display:table;
    }
    form.tr, div.tr
    {
        display:table-row;
    }
    div.td, span.td, div.th, span.th
    {
        display:table-cell;
        width: inherit !important;
    }
    /* bootstrap styling workaround */
    .table > :not(:first-child) {
      border-top: none;
    }
  </style>
{% endblock page_head %}
{% block app %}
  <nav aria-label="breadcrumbs">
    <ol class="pg-breadcrumbs">
      <li class=""><a href="{% url 'pegasus_employees:object_lifecycle_home' %}">Employee Lifecycle App</a></li>
      <li class="pg-breadcrumb-active" aria-current="page">HTMX</li>
    </ol>
  </nav>
  <section class="app-card">
    <div class="pg-columns">
      <div class="pg-column-one-quarter pg-text-centered">
        <img class="img-fluid" alt="HTMX" src="{% static 'images/pegasus/htmx-icon.png' %}" style="max-height: 160px;"/>
      </div>
      <div class="pg-column">
        <h1 class="pg-title">HTMX Object Lifecycle Demo</h1>
        <h2 class="pg-subtitle">
          An interactive data model and UI example.
        </h2>
        <div class="content">
          <p>
            This is an interactive data model and UI example built with <a href="https://htmx.org/" target="_blank">htmx</a>.
            This demo is built with native Django templates and forms and uses no native JavaScript!
          </p>
        </div>
      </div>
    </div>
  </section>
  <div class="app-card">
    <div class="table pg-table">
      <div class="tr">
        <div class="th pg-text-left">Name</div>
        <div class="th pg-text-left">Department</div>
        <div class="th pg-text-right">Salary</div>
        <div class="th"></div>
      </div>
      {% for employee in employees %}
        {% include 'pegasus/employees/htmx/employee_row.html' %}
      {% endfor %}
      {% include 'pegasus/employees/htmx/new_employee_button.html' %}
    </div>
  </div>
{% endblock %}
{% block page_js %}
<script>
  // hook up csrf tokens to all htmx requests
  document.body.addEventListener('htmx:configRequest', (event) => {
    event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
  })
</script>
{% endblock %}

templates/pegasus/employees/list_employees.html
{% extends "pegasus/employees/django_object_lifecycle_base.html" %}
{% load static %}
{% block django_app %}
  <div class="app-card">
    {% if employees %}
      <div class="table-responsive">
        <table class="table pg-table">
          <thead>
          <tr>
            <th class="pg-text-left">Name</th>
            <th class="pg-text-left">Department</th>
            <th class="pg-text-right">Salary</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          {% for employee in employees %}
            <tr>
              <td>{{ employee.name }}</td>
              <td>{{ employee.get_department_display }}</td>
              <td class="pg-text-right">${{ employee.salary }}</td>
              <td class="pg-inline-buttons pg-justify-content-end">
                <a href="{% url 'pegasus_employees:django_edit_employee' employee.id %}">
                  <div class="pg-button-secondary">
                    <span class="icon is-small"><i class="fa fa-edit"></i></span>
                    <span class="pg-hidden-mobile-inline">Edit</span></div>
                </a>
                <form method="post" action="{% url 'pegasus_employees:django_delete_employee' employee.id %}">
                  {% csrf_token %}
                  <button class="pg-button-danger pg-ml" type="submit" value="">
                    <span class="icon is-small"><i class="fa fa-times"></i></span>
                    <span class="pg-hidden-mobile-inline">Delete</span>
                  </button>
                </form>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
      <a class="pg-button-primary" href="{% url 'pegasus_employees:django_new_employee' %}">
        <span class="icon is-small"><i class="fa fa-plus"></i></span>
        <span>Add Employee</span>
      </a>
    {% else %}
      <div class="pg-columns">
        <div class="pg-column-one-third">
          <img class="img-fluid" alt="Nothing Here" src="{% static 'images/undraw/undraw_empty.svg' %}">
        </div>
        <div class="pg-column">
          <h1 class="pg-title">No Employees Yet!</h1>
          <h2 class="pg-subtitle">Create your first employee below to get started.</h2>
          <div class="my-3">
            <a href="{% url 'pegasus_employees:django_new_employee' %}">
              <button class="pg-button-primary">
                <span class="icon is-small"><i class="fa fa-plus"></i></span><span>Create Employee</span>
              </button>
            </a>
          </div>
        </div>
      </div>
    {% endif %}
  </div>
{% endblock %}

templates/pegasus/employees/object_lifecycle.html
{% extends "pegasus/examples/examples_base.html" %}
{% load static %}
{% block app %}
  <nav aria-label="breadcrumbs">
    <ol class="pg-breadcrumbs">
      <li class=""><a href="{% url 'pegasus_employees:object_lifecycle_home' %}">Employee Lifecycle App</a></li>
      <li class="pg-breadcrumb-active" aria-current="page">{{ framework_name }}</li>
    </ol>
  </nav>
  <section class="app-card">
    <div class="pg-columns">
      <div class="pg-column-one-quarter pg-text-centered">
        <img class="img-fluid" alt="{{ framework_name }}" src="{{ framework_icon }}" style="max-height: 160px;"/>
      </div>
      <div class="pg-column">
        <h1 class="pg-title">{{ framework_name }} Object Lifecycle Demo</h1>
        <h2 class="pg-subtitle">
          A single-page interactive data model and UI example.
        </h2>
        <div class="content">
          <p>
            This is an interactive data model and UI example using
            <a href="https://www.django-rest-framework.org/" target="_blank">Django Rest Framework</a> and
            <a href="{{ framework_url }}" target="_blank">{{ framework_name }}</a>.
            It demonstrates performing simple create, read, update and delete (CRUD) operations on an example
            "Employee" data model.
          </p>
        </div>
      </div>
    </div>
  </section>
  <div id="object-lifecycle-home"></div>
{% endblock %}
{% block page_js %}
    {{ department_choices|json_script:'department-choices' }}
    <script>
        // initialize any page specific stuff here
        // static files that are used by the page javascript.
        const STATIC_FILES = {
            'undraw_empty': "{% static 'images/undraw/undraw_empty.svg' %}",
        };
        const EMPLOYEE_DEPARTMENT_CHOICES = JSON.parse(document.getElementById('department-choices').textContent);
        const urlBase = "{{ url_base }}";
    </script>
    <script src="{% static 'rest_framework/js/coreapi-0.1.1.js' %}"></script>
    <script src="{% url 'api_schemajs' %}"></script>
    {% block framework_bundle %}
    {% endblock %}
{% endblock %}

templates/pegasus/employees/react_object_lifecycle.html
{% extends "pegasus/employees/object_lifecycle.html" %}
{% load static %}
{% block framework_bundle %}
  <script src="{% static 'js/react-object-lifecycle-bundle.js' %}"></script>
{% endblock %}

templates/pegasus/employees/vue_object_lifecycle.html
{% extends "pegasus/employees/object_lifecycle.html" %}
{% load static %}
{% block framework_bundle %}
  <script src="{% static 'js/vue-object-lifecycle-bundle.js' %}"></script>
{% endblock %}