apps/web/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'web'
urlpatterns = [
    path('', views.home, name='home'),
    path('terms', TemplateView.as_view(template_name="web/terms.html"), name='terms'),
    path('404', TemplateView.as_view(template_name='404.html'), name='404'),
    path('500', TemplateView.as_view(template_name='500.html'), name='500'),
    path('simulate_error', views.simulate_error),
]

crypto_tax_checker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.documentation import include_docs_urls, get_schemajs_view

schemajs_view = get_schemajs_view(title="API")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('users/', include('apps.users.urls')),
    path('subscriptions/', include('apps.subscriptions.urls')),
    path('', include('apps.web.urls')),
    path('web', include('apps.web.urls')),
    path('pegasus/', include('pegasus.apps.examples.urls')),
    path('pegasus/employees/', include('pegasus.apps.employees.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    # API docs
    # these are needed for schema.js
    path('docs/', include_docs_urls(title='API Docs')),
    path('schemajs/', schemajs_view, name='api_schemajs'),
    # djstripe urls - for webhooks
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
    # Adding my portfolio urls
    path('portfolio/', include('apps.portfolio.urls', namespace="portfolio")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pegasus/apps/examples/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from . import views


app_name = 'pegasus_examples'

urlpatterns = [
    path('', views.ExamplesHomeView.as_view(), name='examples_home'),
    path('payments', views.PaymentView.as_view(), name='payments'),
    # payments via elements
    path('payments/create_payment_intent/', views.create_payment_intent, name='create_payment_intent'),
    path('payments/create/', views.accept_payment, name='accept_payment'),
    path('payments/confirm/<slug:payment_id>/', views.payment_confirm, name='payment_confirm'),
    # payments via checkout
    path('payments/create-checkout-session/', views.create_checkout_session, name='create_checkout_session'),
    path('payments/checkout-success/', views.checkout_success, name='checkout_success'),
    path('payments/checkout-canceled/', views.checkout_canceled, name='checkout_canceled'),

    path('landing_page/', TemplateView.as_view(template_name='pegasus/examples/example_landing_page.html'),
         name='landing_page'),
    path('pricing_page/', TemplateView.as_view(template_name='pegasus/examples/example_pricing_page.html'),
         name='pricing_page'),

    # these are experimental examples that aren't currently exposed in the UI.
    path('alpine/', TemplateView.as_view(template_name='pegasus/examples/alpine_demo.html'), name='alpine_demo'),
    path('forms/', views.ExampleFormView.as_view(), name='form_demo'),

    # tasks
    path('tasks/', views.TasksView.as_view(), name='tasks'),
    path('tasks/api/', views.tasks_api, name='tasks_api'),
]

pegasus/apps/examples/models/payments.py
import uuid

from django.conf import settings
from django.db import models

from apps.utils.models import BaseModel


class Payment(BaseModel):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    charge_id = models.CharField(max_length=100, help_text='The stripe charge ID associated with this payment.')
    name = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='pegasus_payments')
    amount = models.PositiveIntegerField(help_text='In cents')

    @property
    def payment_id(self):
        return str(self.id)

    @property
    def amount_display(self):
        return '${:,.2f}'.format(self.amount / 100.)

pegasus/apps/examples/forms.py
from django import forms


class ExampleForm(forms.Form):
    COLORS = (
        ('red', 'Red'),
        ('blue', 'Blue'),
        ('green', 'Green'),
        ('yellow', 'Yellow'),
    )
    name = forms.CharField(help_text='This is a character field. It is required.')
    email = forms.EmailField(help_text='This is an email field. It is required.')
    checkbox = forms.BooleanField(help_text='This is a checkbox / boolean field', required=False)
    favorite_color = forms.ChoiceField(help_text='This is a choice field', choices=COLORS)
    comments = forms.CharField(help_text='This is a longer character field. It is optional', required=False,
                               widget=forms.Textarea())

pegasus/apps/examples/views/payments_views.py
import stripe
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView

from apps.web.meta import absolute_url
from ..models import Payment

EXPECTED_PAYMENT_AMOUNT = 2500  # in cents


@method_decorator(login_required, name='dispatch')
class PaymentView(TemplateView):
    template_name = 'pegasus/examples/payments/payments.html'

    def get_context_data(self, **kwargs):
        return {
            'stripe_key': settings.STRIPE_TEST_PUBLIC_KEY,
            'payments': self.request.user.pegasus_payments.all(),
            'amount': EXPECTED_PAYMENT_AMOUNT,
            'active_tab': 'payments',
        }


@login_required
@require_POST
def create_payment_intent(request):
    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    intent = stripe.PaymentIntent.create(
        amount=EXPECTED_PAYMENT_AMOUNT,
        currency='usd',
        description=f'A Demo Payment',
    )
    return JsonResponse({
        'client_secret': intent['client_secret'],
    })


@login_required
def payment_confirm(request, payment_id):
    """
    Confirmation page after making a payment.
    """
    payment = get_object_or_404(Payment, user=request.user, id=payment_id)
    return render(request, 'pegasus/examples/payments/payment_confirm.html', {
        'payment': payment,
        'active_tab': 'payments',
    })


@login_required
@require_POST
def accept_payment(request):
    """
    Accept a payment with a token from Stripe
    """
    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    name = request.POST['name']
    try:
        payment_intent_id = request.POST['paymentIntent']
    except KeyError:
        messages.error(request, 'Problem processing that payment. Please try again!')
        return HttpResponseRedirect(reverse('pegasus_examples:payments'))
    payment_intent = stripe.PaymentIntent.retrieve(payment_intent_id)
    if payment_intent.status != 'succeeded':
        raise Exception(f'Unexpected payment intent status: {payment_intent.status}')

    amount = payment_intent['amount']
    if amount != EXPECTED_PAYMENT_AMOUNT:
        raise ValueError(f'Unexpected payment amount {payment_intent["amount"]}')

    charge = payment_intent['charges']['data'][0]

    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    user = request.user
    payment = Payment.objects.create(
        charge_id=charge.id,
        amount=charge.amount,
        name=name,
        user=user,
    )
    return HttpResponseRedirect(reverse('pegasus_examples:payment_confirm', args=[payment.payment_id]))


@require_POST
@login_required
def create_checkout_session(request):
    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    success_url = absolute_url(reverse('pegasus_examples:checkout_success'))
    cancel_url = absolute_url(reverse('pegasus_examples:checkout_canceled'))
    checkout_session = stripe.checkout.Session.create(
        success_url=success_url + '?session_id={CHECKOUT_SESSION_ID}',
        cancel_url=cancel_url,
        customer_email=request.user.email,
        payment_method_types=['card'],
        mode='payment',
        line_items=[{
            'price_data': {
                'currency': 'usd',
                'product_data': {
                    'name': 'Sample Payment',
                },
                'unit_amount': 2500,
            },
            'quantity': 1,
        }],
        allow_promotion_codes=True,
    )
    return HttpResponseRedirect(checkout_session.url)


@login_required
def checkout_success(request):
    session_id = request.GET.get('session_id')
    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    session = stripe.checkout.Session.retrieve(session_id, expand=['payment_intent'])
    assert len(session.payment_intent.charges.data) == 1
    charge_id = session.payment_intent.charges.data[0].id
    payment = Payment.objects.create(
        charge_id=charge_id,
        amount=session.amount_total,
        name='Payment from Checkout',
        user=request.user,
    )
    return HttpResponseRedirect(reverse('pegasus_examples:payment_confirm', args=[payment.payment_id]))


@login_required
def checkout_canceled(request):
    messages.info(request, 'Your payment was canceled.')
    return HttpResponseRedirect(reverse('pegasus_examples:payments'))

pegasus/apps/examples/views/tasks_views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView

from ..tasks import progress_bar_task


@method_decorator(login_required, name='dispatch')
class TasksView(TemplateView):
    template_name = 'pegasus/examples/tasks.html'

    def get_context_data(self, **kwargs):
        return {
            'active_tab': 'tasks',
        }


@require_POST
def tasks_api(request):
    result = progress_bar_task.delay(5)
    return HttpResponse(result.task_id)

templates/pegasus/examples/payments/payment_confirm.html
{% extends "pegasus/examples/examples_base.html" %}
{% load static %}
{% block app %}
  <section class="app-card">
    <div class="pg-columns">
      <div class="pg-column-one-third">
        <img class="img-fluid" src="{% static 'images/undraw/undraw_to_the_stars.svg' %}" alt="You're Off!">
      </div>
      <div class="pg-column">
        <h1 class="pg-title">Hooray!</h1>
        <h2 class="pg-subtitle">
          You just completed a sample payment. Wasn't that easy?
        </h2>
        <p>
          To see your shiny new payment or make another, you can head back to the
          <a href="{% url 'pegasus_examples:payments' %}">payments demo</a>.
        </p>
      </div>
    </div>
  </section>
{% endblock %}

templates/pegasus/examples/payments/payments.html
{% extends "pegasus/examples/examples_base.html" %}
{% block page_head %}
  <script src="https://js.stripe.com/v3/"></script>
{% endblock %}
{% load static %}
{% block app %}
  <section class="app-card">
    <div class="pg-columns">
      <div class="pg-column-one-third">
        <h3 class="pg-title">Payments Example</h3>
        <div class="content">
          <p>
            This example provides an end-to-end workflow for collecting payments using Stripe Elements.
          </p>
          <p>
            You can use any <a href="https://stripe.com/docs/testing#cards" target="_blank">Stripe test card</a>
            to see it in action!
          </p>
        </div>
      </div>
      <div class="pg-column">
        <p class="pg-help">This form is an embedded UI using Stripe elements</p>
        <form action="{% url 'pegasus_examples:accept_payment' %}" method="post" id="payment-form">
          {% csrf_token %}
          <input type="hidden" name="amount" value="{{ amount }}">
          <div class="mb-3">
            <label class="pg-label" for="name">
              Payment Name
            </label>
            <input class="pg-control" type="text" name="name" placeholder="My Amazing Site" id="name-input">
            <div class="pg-help has-text-grey">This name is just for your own records, and can be whatever you want</div>
            <div class="pg-help pg-text-danger" id="name-errors" role="alert"></div>
          </div>
          {% include 'stripe/components/card_element.html' %}
          <div class="mb-3">
            <label class="checkbox">
              <input type="checkbox" name="consent" id="consent-checkbox">
              I agree to the <a href="{% url 'web:terms' %}" target="_blank">terms and conditions</a>
            </label>
            <div class="pg-help pg-text-danger" id="terms-errors" role="alert"></div>
          </div>
          <button class="pg-button-primary" id="purchase-button">Pay $25</button>
        </form>
        <hr>
        <p class="pg-help">Alternatively, you can use Stripe Checkout to handle the entire payment flow.</p>
        <form action="{% url 'pegasus_examples:create_checkout_session' %}" method="POST" >
          {% csrf_token %}
          <input type="hidden" name="priceId" value="{{ product.price_object.id }}">
          <button type="submit" class="pg-button-primary mt-2" >Pay with Checkout</button>
        </form>
      </div>
    </div>
  </section>
  {% if payments %}
    <section class="app-card">
      <h3 class="pg-title">My Payments</h3>
      <div class='table-responsive'>
        <table class="table is-striped is-fullwidth">
          <thead>
          <tr>
            <th>Payments Name</th>
            <th>Payment Date</th>
            <th>Payment Amount</th>
          </tr>
          </thead>
          <tbody>
          {% for payment in payments %}
            <tr>
              <td>{{ payment.name }}</td>
              <td>{{ payment.created_at }}</td>
              <td>{{ payment.amount_display }}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </section>
  {% else %}
    <section class="app-card notification is-warning is-light">
      <div class="content">
        <p>
          No payments yet! Make a payment using any <a href="https://stripe.com/docs/testing#cards"
                                                       target="_blank">Stripe test card</a>
          to see the rest of the demo.
        </p>
        <p>
          Hint: you can use card number <strong>4242 4242 4242 4242</strong> and any expiration date / CVC /
          zipcode.
        </p>
      </div>
    </section>
  {% endif %}
{% endblock %}
{% block page_js %}
  <script src="{% static 'js/app-bundle.js' %}"></script>
  <script>
    const Payments = SiteJS.app.Payments;

    const createPaymentIntentUrl = "{% url 'pegasus_examples:create_payment_intent' %}";
    const stripe = Stripe('{{ stripe_key }}');

    const form = document.getElementById('payment-form');

    const validateForm = function() {
      // do form validation and return whether or not there were any errors
      let hasErrors = false;
      const nameErrorElement = document.getElementById('name-errors');
      if (!document.getElementById('name-input').value) {
        nameErrorElement.textContent = 'Name is required.';
        hasErrors = true;
      } else {
        nameErrorElement.textContent = '';
      }
      const termsErrorElement = document.getElementById('terms-errors');
      if (!document.getElementById('consent-checkbox').checked) {
        termsErrorElement.textContent = 'Please agree to the terms and conditions.';
        hasErrors = true;
      } else {
        termsErrorElement.textContent = '';
      }
      return hasErrors;
    };
    Payments.createPaymentIntent(createPaymentIntentUrl).then((clientSecret) => {
      const card = Payments.createCardElement(stripe);
      form.addEventListener('submit', function (event) {
        event.preventDefault();
        const hasErrors = validateForm();
        if (!hasErrors) {
          payWithCard(stripe, card, clientSecret);
        }
      });
    });

    const payWithCard = function(stripe, card, clientSecret) {
      const purchaseButton = document.getElementById('purchase-button');
      purchaseButton.classList.add('pg-is-loading');
      stripe.confirmCardPayment(clientSecret, {
        payment_method: {
          card: card,
        }
      })
      .then(function(result) {
        if (result.error) {
          // Show error to your customer
          Payments.showOrClearError(result.error.message);
          purchaseButton.classList.remove('pg-is-loading');
        } else {
          // The payment succeeded!
          // do server-side processing on our side
          Payments.addInputToForm(form, 'paymentIntent', result.paymentIntent.id);
          form.submit();
        }
      });
    };
  </script>
{% endblock %}