crypto_tax_checker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.documentation import include_docs_urls, get_schemajs_view

schemajs_view = get_schemajs_view(title="API")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('users/', include('apps.users.urls')),
    path('subscriptions/', include('apps.subscriptions.urls')),
    path('', include('apps.web.urls')),
    path('web', include('apps.web.urls')),
    path('pegasus/', include('pegasus.apps.examples.urls')),
    path('pegasus/employees/', include('pegasus.apps.employees.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    # API docs
    # these are needed for schema.js
    path('docs/', include_docs_urls(title='API Docs')),
    path('schemajs/', schemajs_view, name='api_schemajs'),
    # djstripe urls - for webhooks
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
    # Adding my portfolio urls
    path('portfolio/', include('apps.portfolio.urls', namespace="portfolio")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pegasus/apps/employees/urls.py
from django.urls import path
from django.views.generic import TemplateView
from rest_framework import routers

from . import views


app_name = 'pegasus_employees'

urlpatterns = [
    path('objects/', TemplateView.as_view(template_name='pegasus/employees/object_lifecycle_home.html',
                                          extra_context={'active_tab': 'object_lifecycle'}),
         name='object_lifecycle_home', ),
    path('objects/django/', views.employee_list, name='django_object_lifecycle'),
    path('objects/django/new/', views.new_employee, name='django_new_employee'),
    path('objects/django/edit/<int:employee_id>/', views.edit_employee, name='django_edit_employee'),
    path('objects/django/delete/<int:employee_id>/', views.delete_employee, name='django_delete_employee'),

    path('objects/htmx/', views.employee_list_htmx, name='htmx_object_lifecycle'),
    path('objects/htmx/new/', views.new_employee_row_htmx, name='htmx_new_employee'),
    path('objects/htmx/empty/', views.empty_htmx, name='htmx_empty'),

    path('objects/htmx/edit/<int:employee_id>/', views.edit_employee_row_htmx, name='htmx_edit_employee'),
    path('objects/htmx/get/<int:employee_id>/', views.get_employee_row_htmx, name='htmx_get_employee'),
    path('objects/htmx/delete/<int:employee_id>/', views.delete_employee_htmx, name='htmx_delete_employee'),

    path('objects/react/', views.ReactObjectLifecycleView.as_view(), name='react_object_lifecycle'),
    path('objects/react/<path:path>', views.ReactObjectLifecycleView.as_view(), name='react_object_lifecycle_w_path'),
    path('objects/vue/', views.VueObjectLifecycleView.as_view(), name='vue_object_lifecycle'),
    path('charts/', views.ChartsView.as_view(), name='charts'),

    path('api/employee-data/', views.EmployeeDataAPIView.as_view(), name='employee_data'),
]


# drf config
router = routers.DefaultRouter()
router.register('api/employees', views.EmployeeViewSet)

urlpatterns += router.urls

pegasus/apps/examples/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from . import views


app_name = 'pegasus_examples'

urlpatterns = [
    path('', views.ExamplesHomeView.as_view(), name='examples_home'),
    path('payments', views.PaymentView.as_view(), name='payments'),
    # payments via elements
    path('payments/create_payment_intent/', views.create_payment_intent, name='create_payment_intent'),
    path('payments/create/', views.accept_payment, name='accept_payment'),
    path('payments/confirm/<slug:payment_id>/', views.payment_confirm, name='payment_confirm'),
    # payments via checkout
    path('payments/create-checkout-session/', views.create_checkout_session, name='create_checkout_session'),
    path('payments/checkout-success/', views.checkout_success, name='checkout_success'),
    path('payments/checkout-canceled/', views.checkout_canceled, name='checkout_canceled'),

    path('landing_page/', TemplateView.as_view(template_name='pegasus/examples/example_landing_page.html'),
         name='landing_page'),
    path('pricing_page/', TemplateView.as_view(template_name='pegasus/examples/example_pricing_page.html'),
         name='pricing_page'),

    # these are experimental examples that aren't currently exposed in the UI.
    path('alpine/', TemplateView.as_view(template_name='pegasus/examples/alpine_demo.html'), name='alpine_demo'),
    path('forms/', views.ExampleFormView.as_view(), name='form_demo'),

    # tasks
    path('tasks/', views.TasksView.as_view(), name='tasks'),
    path('tasks/api/', views.tasks_api, name='tasks_api'),
]

pegasus/apps/examples/models/payments.py
import uuid

from django.conf import settings
from django.db import models

from apps.utils.models import BaseModel


class Payment(BaseModel):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    charge_id = models.CharField(max_length=100, help_text='The stripe charge ID associated with this payment.')
    name = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='pegasus_payments')
    amount = models.PositiveIntegerField(help_text='In cents')

    @property
    def payment_id(self):
        return str(self.id)

    @property
    def amount_display(self):
        return '${:,.2f}'.format(self.amount / 100.)

pegasus/apps/examples/forms.py
from django import forms


class ExampleForm(forms.Form):
    COLORS = (
        ('red', 'Red'),
        ('blue', 'Blue'),
        ('green', 'Green'),
        ('yellow', 'Yellow'),
    )
    name = forms.CharField(help_text='This is a character field. It is required.')
    email = forms.EmailField(help_text='This is an email field. It is required.')
    checkbox = forms.BooleanField(help_text='This is a checkbox / boolean field', required=False)
    favorite_color = forms.ChoiceField(help_text='This is a choice field', choices=COLORS)
    comments = forms.CharField(help_text='This is a longer character field. It is optional', required=False,
                               widget=forms.Textarea())

pegasus/apps/examples/views/payments_views.py
import stripe
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView

from apps.web.meta import absolute_url
from ..models import Payment

EXPECTED_PAYMENT_AMOUNT = 2500  # in cents


@method_decorator(login_required, name='dispatch')
class PaymentView(TemplateView):
    template_name = 'pegasus/examples/payments/payments.html'

    def get_context_data(self, **kwargs):
        return {
            'stripe_key': settings.STRIPE_TEST_PUBLIC_KEY,
            'payments': self.request.user.pegasus_payments.all(),
            'amount': EXPECTED_PAYMENT_AMOUNT,
            'active_tab': 'payments',
        }


@login_required
@require_POST
def create_payment_intent(request):
    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    intent = stripe.PaymentIntent.create(
        amount=EXPECTED_PAYMENT_AMOUNT,
        currency='usd',
        description=f'A Demo Payment',
    )
    return JsonResponse({
        'client_secret': intent['client_secret'],
    })


@login_required
def payment_confirm(request, payment_id):
    """
    Confirmation page after making a payment.
    """
    payment = get_object_or_404(Payment, user=request.user, id=payment_id)
    return render(request, 'pegasus/examples/payments/payment_confirm.html', {
        'payment': payment,
        'active_tab': 'payments',
    })


@login_required
@require_POST
def accept_payment(request):
    """
    Accept a payment with a token from Stripe
    """
    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    name = request.POST['name']
    try:
        payment_intent_id = request.POST['paymentIntent']
    except KeyError:
        messages.error(request, 'Problem processing that payment. Please try again!')
        return HttpResponseRedirect(reverse('pegasus_examples:payments'))
    payment_intent = stripe.PaymentIntent.retrieve(payment_intent_id)
    if payment_intent.status != 'succeeded':
        raise Exception(f'Unexpected payment intent status: {payment_intent.status}')

    amount = payment_intent['amount']
    if amount != EXPECTED_PAYMENT_AMOUNT:
        raise ValueError(f'Unexpected payment amount {payment_intent["amount"]}')

    charge = payment_intent['charges']['data'][0]

    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    user = request.user
    payment = Payment.objects.create(
        charge_id=charge.id,
        amount=charge.amount,
        name=name,
        user=user,
    )
    return HttpResponseRedirect(reverse('pegasus_examples:payment_confirm', args=[payment.payment_id]))


@require_POST
@login_required
def create_checkout_session(request):
    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    success_url = absolute_url(reverse('pegasus_examples:checkout_success'))
    cancel_url = absolute_url(reverse('pegasus_examples:checkout_canceled'))
    checkout_session = stripe.checkout.Session.create(
        success_url=success_url + '?session_id={CHECKOUT_SESSION_ID}',
        cancel_url=cancel_url,
        customer_email=request.user.email,
        payment_method_types=['card'],
        mode='payment',
        line_items=[{
            'price_data': {
                'currency': 'usd',
                'product_data': {
                    'name': 'Sample Payment',
                },
                'unit_amount': 2500,
            },
            'quantity': 1,
        }],
        allow_promotion_codes=True,
    )
    return HttpResponseRedirect(checkout_session.url)


@login_required
def checkout_success(request):
    session_id = request.GET.get('session_id')
    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    session = stripe.checkout.Session.retrieve(session_id, expand=['payment_intent'])
    assert len(session.payment_intent.charges.data) == 1
    charge_id = session.payment_intent.charges.data[0].id
    payment = Payment.objects.create(
        charge_id=charge_id,
        amount=session.amount_total,
        name='Payment from Checkout',
        user=request.user,
    )
    return HttpResponseRedirect(reverse('pegasus_examples:payment_confirm', args=[payment.payment_id]))


@login_required
def checkout_canceled(request):
    messages.info(request, 'Your payment was canceled.')
    return HttpResponseRedirect(reverse('pegasus_examples:payments'))

pegasus/apps/examples/views/tasks_views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView

from ..tasks import progress_bar_task


@method_decorator(login_required, name='dispatch')
class TasksView(TemplateView):
    template_name = 'pegasus/examples/tasks.html'

    def get_context_data(self, **kwargs):
        return {
            'active_tab': 'tasks',
        }


@require_POST
def tasks_api(request):
    result = progress_bar_task.delay(5)
    return HttpResponse(result.task_id)

templates/pegasus/examples/components/bootstrap_not_supported.html
<p>
  The Bootstrap version of Pegasus doesn't ship with a marketing site,
  since they are readily available elsewhere.
</p>
<p>
  Here's <a href="https://dev.to/bootstrap/bootstrap-5-templates-91p" target="_blank">a list of great landing page and marketing site options</a>
  that are free for personal use.
  Or, for under $50, we recommend one of the <a href="https://themes.getbootstrap.com/" target="_blank">official Bootstrap themes</a>.
</p>

templates/pegasus/examples/components/examples_nav.html
<aside style="min-width: 200px;">
  <div class="mb-1">
    Pegasus Examples
  </div>
  <ul class="nav nav-pills flex-column">
    <li class="nav-item">
      <a href="{% url 'pegasus_examples:examples_home' %}" class="nav-link {% if active_tab == 'home' %}active{% endif %}">
        <span class="icon"><i class="fa fa-home"></i></span><span>Examples Home</span>
      </a>
    </li>
    <li class="nav-item">
      <a href="{% url 'pegasus_examples:payments' %}" class="nav-link {% if active_tab == 'payments' %}active{% endif %}">
        <span class="icon"><i class="fa fa-credit-card"></i></span><span>Payments</span>
      </a>
    </li>
    <li class="nav-item">
      <a href="{% url 'pegasus_employees:object_lifecycle_home' %}" class="nav-link {% if active_tab == 'object_lifecycle' %}active{% endif %}">
        <span class="icon"><i class="fa fa-users"></i></span><span>Employee App</span>
      </a>
    </li>
    <li class="nav-item">
      <a href="{% url 'pegasus_examples:tasks' %}" class="nav-link {% if active_tab == 'tasks' %}active{% endif %}">
        <span class="icon"><i class="fa fa-tasks"></i></span><span>Background Tasks</span>
      </a>
    </li>
    <li class="nav-item">
      <a href="{% url 'pegasus_employees:charts' %}" class="nav-link {% if active_tab == 'charts' %}active{% endif %}">
        <span class="icon"><i class="fa fa-bar-chart-o"></i></span><span>Charts</span>
      </a>
    </li>
    <li class="nav-item">
      <a href="{% url 'pegasus_examples:landing_page' %}" class="nav-link">
        <span class="icon"><i class="fa fa-picture-o"></i></span><span>Landing Page</span>
      </a>
    </li>
    <li>
      <a href="{% url 'pegasus_examples:pricing_page' %}" class="nav-link">
        <span class="icon"><i class="fa fa-external-link"></i></span><span>Pricing Page</span>
      </a>
    </li>
  </ul>
</aside>

templates/pegasus/examples/components/sticky-header-js.html
<script>
    // sticky header - see https://coder-coder.com/sticky-header-animated/ for details
    var checkHeader = function () {
        var scrollPosition = Math.round(window.scrollY);
        if (scrollPosition > 52){
            document.querySelector('.app-notice').classList.add('sticky');
            document.querySelector('#example-page-content').classList.add('sticky-offset');
        }
        // If not, remove "sticky" class from header
        else {
            document.querySelector('.app-notice').classList.remove('sticky');
            document.querySelector('#example-page-content').classList.remove('sticky-offset');
        }
    };
    window.addEventListener('scroll', checkHeader);
</script>