crypto_tax_checker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.documentation import include_docs_urls, get_schemajs_view

schemajs_view = get_schemajs_view(title="API")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('users/', include('apps.users.urls')),
    path('subscriptions/', include('apps.subscriptions.urls')),
    path('', include('apps.web.urls')),
    path('web', include('apps.web.urls')),
    path('pegasus/', include('pegasus.apps.examples.urls')),
    path('pegasus/employees/', include('pegasus.apps.employees.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    # API docs
    # these are needed for schema.js
    path('docs/', include_docs_urls(title='API Docs')),
    path('schemajs/', schemajs_view, name='api_schemajs'),
    # djstripe urls - for webhooks
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
    # Adding my portfolio urls
    path('portfolio/', include('apps.portfolio.urls', namespace="portfolio")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pegasus/apps/employees/urls.py
from django.urls import path
from django.views.generic import TemplateView
from rest_framework import routers

from . import views


app_name = 'pegasus_employees'

urlpatterns = [
    path('objects/', TemplateView.as_view(template_name='pegasus/employees/object_lifecycle_home.html',
                                          extra_context={'active_tab': 'object_lifecycle'}),
         name='object_lifecycle_home', ),
    path('objects/django/', views.employee_list, name='django_object_lifecycle'),
    path('objects/django/new/', views.new_employee, name='django_new_employee'),
    path('objects/django/edit/<int:employee_id>/', views.edit_employee, name='django_edit_employee'),
    path('objects/django/delete/<int:employee_id>/', views.delete_employee, name='django_delete_employee'),

    path('objects/htmx/', views.employee_list_htmx, name='htmx_object_lifecycle'),
    path('objects/htmx/new/', views.new_employee_row_htmx, name='htmx_new_employee'),
    path('objects/htmx/empty/', views.empty_htmx, name='htmx_empty'),

    path('objects/htmx/edit/<int:employee_id>/', views.edit_employee_row_htmx, name='htmx_edit_employee'),
    path('objects/htmx/get/<int:employee_id>/', views.get_employee_row_htmx, name='htmx_get_employee'),
    path('objects/htmx/delete/<int:employee_id>/', views.delete_employee_htmx, name='htmx_delete_employee'),

    path('objects/react/', views.ReactObjectLifecycleView.as_view(), name='react_object_lifecycle'),
    path('objects/react/<path:path>', views.ReactObjectLifecycleView.as_view(), name='react_object_lifecycle_w_path'),
    path('objects/vue/', views.VueObjectLifecycleView.as_view(), name='vue_object_lifecycle'),
    path('charts/', views.ChartsView.as_view(), name='charts'),

    path('api/employee-data/', views.EmployeeDataAPIView.as_view(), name='employee_data'),
]


# drf config
router = routers.DefaultRouter()
router.register('api/employees', views.EmployeeViewSet)

urlpatterns += router.urls

pegasus/apps/examples/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from . import views


app_name = 'pegasus_examples'

urlpatterns = [
    path('', views.ExamplesHomeView.as_view(), name='examples_home'),
    path('payments', views.PaymentView.as_view(), name='payments'),
    # payments via elements
    path('payments/create_payment_intent/', views.create_payment_intent, name='create_payment_intent'),
    path('payments/create/', views.accept_payment, name='accept_payment'),
    path('payments/confirm/<slug:payment_id>/', views.payment_confirm, name='payment_confirm'),
    # payments via checkout
    path('payments/create-checkout-session/', views.create_checkout_session, name='create_checkout_session'),
    path('payments/checkout-success/', views.checkout_success, name='checkout_success'),
    path('payments/checkout-canceled/', views.checkout_canceled, name='checkout_canceled'),

    path('landing_page/', TemplateView.as_view(template_name='pegasus/examples/example_landing_page.html'),
         name='landing_page'),
    path('pricing_page/', TemplateView.as_view(template_name='pegasus/examples/example_pricing_page.html'),
         name='pricing_page'),

    # these are experimental examples that aren't currently exposed in the UI.
    path('alpine/', TemplateView.as_view(template_name='pegasus/examples/alpine_demo.html'), name='alpine_demo'),
    path('forms/', views.ExampleFormView.as_view(), name='form_demo'),

    # tasks
    path('tasks/', views.TasksView.as_view(), name='tasks'),
    path('tasks/api/', views.tasks_api, name='tasks_api'),
]

pegasus/apps/employees/forms.py
from django import forms

from .models import Employee


class EmployeeForm(forms.ModelForm):

    class Meta:
        model = Employee
        fields = ('name', 'department', 'salary')

pegasus/apps/employees/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Avg, Sum, Count
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.templatetags.static import static
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST, require_http_methods
from django.views.generic import TemplateView
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.views import APIView

from .forms import EmployeeForm
from .models import Employee
from .serializers import EmployeeSerializer


@login_required
def employee_list(request):
    return render(request, 'pegasus/employees/list_employees.html', {
        'active_tab': 'object_lifecycle',
        'employees': Employee.objects.filter(user=request.user)
    })


@login_required
def new_employee(request):
    return _add_edit_employee(request)


@login_required
def edit_employee(request, employee_id):
    # don't forget to filter by user, else you'll allow people to edit other people's employees!
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    return _add_edit_employee(request, employee)


def _add_edit_employee(request, employee: Employee = None):
    if employee:
        assert employee.user == request.user
    if request.method == 'POST':
        form = EmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            employee = form.save(commit=False)
            employee.user = request.user
            employee.save()
            return HttpResponseRedirect(reverse('pegasus_employees:django_object_lifecycle'))
    else:
        form = EmployeeForm(instance=employee)

    return render(request, 'pegasus/employees/edit_employee.html', {
        'active_tab': 'object_lifecycle',
        'employee': employee,
        'form': form,
    })


@require_POST
@login_required
def delete_employee(request, employee_id):
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    employee.delete()
    return HttpResponseRedirect(reverse('pegasus_employees:django_object_lifecycle'))


@login_required
def employee_list_htmx(request):
    return render(request, 'pegasus/employees/htmx_object_lifecycle.html', {
        'active_tab': 'object_lifecycle',
        'employees': Employee.objects.filter(user=request.user)
    })


@login_required
def new_employee_row_htmx(request):
    return _add_edit_employee_htmx(request)


@login_required
def edit_employee_row_htmx(request, employee_id):
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    return _add_edit_employee_htmx(request, employee)


def _add_edit_employee_htmx(request, employee=None):
    if request.method == 'POST':
        form = EmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            employee = form.save(commit=False)
            employee.user = request.user
            employee.save()
            return HttpResponseRedirect(reverse('pegasus_employees:htmx_get_employee', args=[employee.id]))
    else:
        form = EmployeeForm(instance=employee)

    return render(request, 'pegasus/employees/htmx/edit_employee_row.html', {
        'employee': employee,
        'form': form,
    })


def empty_htmx(request):
    return HttpResponse('')


@login_required
def get_employee_row_htmx(request, employee_id):
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    return render(request, 'pegasus/employees/htmx/employee_row.html', {
        'employee': employee,
    })


@require_http_methods(['DELETE'])
@login_required
def delete_employee_htmx(request, employee_id):
    employee = get_object_or_404(Employee, user=request.user, id=employee_id)
    employee.delete()
    return HttpResponse('')


@method_decorator(login_required, name='dispatch')
class ObjectLifecycleView(TemplateView):
    def get_context_data(self, **kwargs):
        return {
            'department_choices': [{
                'id': c[0],
                'name': c[1]
            } for c in Employee.DEPARTMENT_CHOICES],
        }


class ReactObjectLifecycleView(ObjectLifecycleView):
    template_name = 'pegasus/employees/react_object_lifecycle.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'framework_url': 'https://reactjs.org/',
            'framework_name': 'React',
            'framework_icon': static('images/pegasus/react-icon.png'),
            'active_tab': 'object_lifecycle',
            'url_base': reverse('pegasus_employees:react_object_lifecycle'),
        })
        return context


class VueObjectLifecycleView(ObjectLifecycleView):
    template_name = 'pegasus/employees/vue_object_lifecycle.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'framework_url': 'https://vuejs.org/',
            'framework_name': 'Vue.js',
            'framework_icon': static('images/pegasus/vue-icon.png'),
            'active_tab': 'object_lifecycle',
            'url_base': reverse('pegasus_employees:vue_object_lifecycle'),
        })
        return context


@method_decorator(login_required, name='dispatch')
class ChartsView(TemplateView):
    template_name = 'pegasus/employees/charts.html'

    def get_context_data(self, **kwargs):
        return {
            'active_tab': 'charts',
        }


class EmployeeDataAPIView(APIView):

    def get(self, request):
        user = request.user
        data = user.employees.values('department').annotate(
            average_salary=Avg('salary'),
            total_cost=Sum('salary'),
            number_employees=Count('pk'),
        )
        # data will look something like this:
        # [
        #     {'total_cost': 132000, 'number_employees': 2, 'average_salary': 66000.0, 'department': 'hr'},
        #     {'total_cost': 60000, 'number_employees': 1, 'average_salary': 60000.0, 'department': 'marketing'}
        # ]
        total_costs = [
            [row['department'], row['total_cost']] for row in data
        ]
        average_salaries = [
            [row['department'], row['average_salary']] for row in data
        ]
        headcounts = [
            [row['department'], row['number_employees']] for row in data
        ]
        return Response({
            'total_costs': total_costs,
            'average_salaries': average_salaries,
            'headcounts': headcounts,
        })


class EmployeeViewSet(viewsets.ModelViewSet):
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer

    def get_queryset(self):
        # filter queryset based on logged in user
        return self.request.user.employees.all()

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

pegasus/apps/examples/views/payments_views.py
import stripe
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView

from apps.web.meta import absolute_url
from ..models import Payment

EXPECTED_PAYMENT_AMOUNT = 2500  # in cents


@method_decorator(login_required, name='dispatch')
class PaymentView(TemplateView):
    template_name = 'pegasus/examples/payments/payments.html'

    def get_context_data(self, **kwargs):
        return {
            'stripe_key': settings.STRIPE_TEST_PUBLIC_KEY,
            'payments': self.request.user.pegasus_payments.all(),
            'amount': EXPECTED_PAYMENT_AMOUNT,
            'active_tab': 'payments',
        }


@login_required
@require_POST
def create_payment_intent(request):
    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    intent = stripe.PaymentIntent.create(
        amount=EXPECTED_PAYMENT_AMOUNT,
        currency='usd',
        description=f'A Demo Payment',
    )
    return JsonResponse({
        'client_secret': intent['client_secret'],
    })


@login_required
def payment_confirm(request, payment_id):
    """
    Confirmation page after making a payment.
    """
    payment = get_object_or_404(Payment, user=request.user, id=payment_id)
    return render(request, 'pegasus/examples/payments/payment_confirm.html', {
        'payment': payment,
        'active_tab': 'payments',
    })


@login_required
@require_POST
def accept_payment(request):
    """
    Accept a payment with a token from Stripe
    """
    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    name = request.POST['name']
    try:
        payment_intent_id = request.POST['paymentIntent']
    except KeyError:
        messages.error(request, 'Problem processing that payment. Please try again!')
        return HttpResponseRedirect(reverse('pegasus_examples:payments'))
    payment_intent = stripe.PaymentIntent.retrieve(payment_intent_id)
    if payment_intent.status != 'succeeded':
        raise Exception(f'Unexpected payment intent status: {payment_intent.status}')

    amount = payment_intent['amount']
    if amount != EXPECTED_PAYMENT_AMOUNT:
        raise ValueError(f'Unexpected payment amount {payment_intent["amount"]}')

    charge = payment_intent['charges']['data'][0]

    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    user = request.user
    payment = Payment.objects.create(
        charge_id=charge.id,
        amount=charge.amount,
        name=name,
        user=user,
    )
    return HttpResponseRedirect(reverse('pegasus_examples:payment_confirm', args=[payment.payment_id]))


@require_POST
@login_required
def create_checkout_session(request):
    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    success_url = absolute_url(reverse('pegasus_examples:checkout_success'))
    cancel_url = absolute_url(reverse('pegasus_examples:checkout_canceled'))
    checkout_session = stripe.checkout.Session.create(
        success_url=success_url + '?session_id={CHECKOUT_SESSION_ID}',
        cancel_url=cancel_url,
        customer_email=request.user.email,
        payment_method_types=['card'],
        mode='payment',
        line_items=[{
            'price_data': {
                'currency': 'usd',
                'product_data': {
                    'name': 'Sample Payment',
                },
                'unit_amount': 2500,
            },
            'quantity': 1,
        }],
        allow_promotion_codes=True,
    )
    return HttpResponseRedirect(checkout_session.url)


@login_required
def checkout_success(request):
    session_id = request.GET.get('session_id')
    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    session = stripe.checkout.Session.retrieve(session_id, expand=['payment_intent'])
    assert len(session.payment_intent.charges.data) == 1
    charge_id = session.payment_intent.charges.data[0].id
    payment = Payment.objects.create(
        charge_id=charge_id,
        amount=session.amount_total,
        name='Payment from Checkout',
        user=request.user,
    )
    return HttpResponseRedirect(reverse('pegasus_examples:payment_confirm', args=[payment.payment_id]))


@login_required
def checkout_canceled(request):
    messages.info(request, 'Your payment was canceled.')
    return HttpResponseRedirect(reverse('pegasus_examples:payments'))

pegasus/apps/examples/views/tasks_views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView

from ..tasks import progress_bar_task


@method_decorator(login_required, name='dispatch')
class TasksView(TemplateView):
    template_name = 'pegasus/examples/tasks.html'

    def get_context_data(self, **kwargs):
        return {
            'active_tab': 'tasks',
        }


@require_POST
def tasks_api(request):
    result = progress_bar_task.delay(5)
    return HttpResponse(result.task_id)

templates/pegasus/examples/alpine_demo.html
{% extends "pegasus/examples/examples_base.html" %}
{% load static %}
{% block page_head %}
  <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
{% endblock page_head %}
{% block app %}
  <div class="app-card">
    <h1 class="pg-title">AlpineJS Demo</h1>
    <h2 x-data="{ message: 'I ❤️ Alpine' }" x-text="message" class="pg-subtitle"></h2>
    <div x-data="{ count: 0 }" class="mt-2">
      <button x-on:click="count++" class="pg-button-secondary">Increment</button>
      <span x-text="count"></span>
    </div>
    <div x-data="{ open: false }" class="mt-2">
      <button @click="open = ! open" class="pg-button-secondary">Toggle</button>
      <div x-show="open" @click.outside="open = false" class="mt-1">Contents...</div>
    </div>
    <div class="mt-2"
      x-data="{
          search: '',

          items: ['foo', 'bar', 'baz'],

          filteredItems() {
              return this.items.filter(
                  i => i.startsWith(this.search)
              )
          }
      }"
  >
      <input x-model="search" placeholder="Search..." class="pg-control">

      <ul class="mt-1">
          <template x-for="item in filteredItems()" :key="item">
              <li x-text="item"></li>
          </template>
      </ul>
    </div>
  </div>
{% endblock %}

templates/pegasus/examples/example_form.html
{% extends "pegasus/examples/examples_base.html" %}
{% load static %}
{% load form_tags %}
{% block app %}
<section class="app-card">
  <h2 class="pg-subtitle">Example Form</h2>
  <form method="post">
    {% csrf_token %}
    {% render_form_fields form %}
    <input type="submit" value="Save Data" class="pg-button-secondary">
  </form>
</section>
{% endblock %}

templates/pegasus/examples/example_landing_page.html
{% extends "pegasus/examples/examples_base.html" %}
{% block app %}
  <section class="app-card">
    <h3>Need a landing page?</h3>
    {% include 'pegasus/examples/components/bootstrap_not_supported.html' %}
  </section>
{% endblock %}

templates/pegasus/examples/example_pricing_page.html
{% extends "pegasus/examples/examples_base.html" %}
{% block app %}
  <section class="app-card">
    <h3>Need a pricing page?</h3>
    {% include 'pegasus/examples/components/bootstrap_not_supported.html' %}
  </section>
{% endblock %}

templates/pegasus/examples/examples_base.html
{% extends "web/app/app_base.html" %}
{% block sidebar-nav %}
    {% include "pegasus/examples/components/examples_nav.html" %}
{% endblock %}

templates/pegasus/examples/examples_home.html
{% extends "pegasus/examples/examples_base.html" %}
{% load static %}
{% block app %}
<section class="app-card">
  <h1 class="pg-title">Examples Gallery</h1>
  <h2 class="pg-subtitle">
    End-to-end, fully functional examples for your project's needs.
  </h2>
</section>
  <div class="pg-columns">
    <div class="pg-column">
      <div class="pg-card h-100">
        <div class="pg-card-image">
          <figure class="image pg-ratio-3x2">
            <img class="img-fluid" src="{% static 'images/undraw/undraw_credit_card.svg' %}" alt="Payments">
          </figure>
        </div>
        <div class="pg-card-body">
          <div class="content">
            <h3>Payments</h3>
            <p>
              Easily collect once-off credit card payments using Stripe
              with this complete example.
            </p>
          </div>
          <div class="buttons">
            <a href="{% url 'pegasus_examples:payments' %}" class="pg-button-secondary">
              <span>View Payments</span>
              <span class="icon">
                <i class="fa fa-angle-double-right"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="pg-column">
      <div class="pg-card h-100">
        <div class="pg-card-image">
          <figure class="image pg-ratio-3x2">
            <img class="img-fluid" src="{% static 'images/pegasus/object-demo-icons.png' %}" alt="Object Demo">
          </figure>
        </div>
        <div class="pg-card-body">
          <div class="content">
            <h3>Employee Lifecycle</h3>
            <p>
              A front-end for working with your database implemented in vanilla Django, React, Vue.js, and HTMX.
            </p>
          </div>
          <div class="buttons">
            <a href="{% url 'pegasus_employees:object_lifecycle_home' %}" class="pg-button-secondary">
              <span>View Employee App</span>
              <span class="icon">
                <i class="fa fa-angle-double-right"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="pg-column">
      <div class="pg-card h-100">
        <div class="pg-card-image">
          <figure class="image pg-ratio-3x2">
            <img class="img-fluid" src="{% static 'images/pegasus/celery-icon.png' %}" alt="Background Tasks">
          </figure>
        </div>
        <div class="pg-card-body">
          <div class="content">
            <h3>Background Tasks</h3>
            <p>
              Support background, long-running, or scheduled tasks easily with a working Celery
              + front-end integration.
            </p>
          </div>
          <div class="buttons">
            <a href="{% url 'pegasus_examples:tasks' %}" class="pg-button-secondary">
              <span>View Tasks</span>
              <span class="icon">
                <i class="fa fa-angle-double-right"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="pg-columns mt-2">
    <div class="pg-column">
      <div class="pg-card h-100">
        <div class="pg-card-image">
          <figure class="image pg-ratio-3x2">
            <img class="img-fluid" src="{% static 'images/undraw/undraw_analytics.svg' %}" alt="Charts">
          </figure>
        </div>
        <div class="pg-card-body">
          <div class="content">
            <h3>Charts</h3>
            <p>
              Fully-integrated charts based on real data from your application.
            </p>
          </div>
          <div class="buttons">
            <a href="{% url 'pegasus_employees:charts' %}" class="pg-button-secondary">
              <span>View Charts</span>
              <span class="icon">
                <i class="fa fa-angle-double-right"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="pg-column">
      <div class="pg-card h-100">
        <div class="pg-card-image">
          <figure class="image pg-ratio-3x2">
            <img class="img-fluid" src="{% static 'images/pegasus/landing-page-screenshot-small.png' %}" alt="Landing Page">
          </figure>
        </div>
        <div class="pg-card-body">
          <div class="content">
            <h3>Landing Page</h3>
            <p>
              A beautiful, responsive, and easy-to-customize landing page to help
              you tell your application's story.
            </p>
          </div>
          <div class="buttons">
            <a href="{% url 'pegasus_examples:landing_page' %}" class="pg-button-secondary">
              <span>View Landing Page</span>
              <span class="icon">
                <i class="fa fa-angle-double-right"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="pg-column">
      <div class="pg-card h-100">
        <div class="pg-card-image">
          <figure class="image pg-ratio-3x2">
            <img class="img-fluid" src="{% static 'images/pegasus/pricing-page-screenshot-small.png' %}" alt="Pricing Page">
          </figure>
        </div>
        <div class="pg-card-body">
          <div class="content">
            <h3>Pricing Page</h3>
            <p>
              Communicate your application's value with a simple, flexible
              pricing page.
            </p>
          </div>
          <div class="buttons">
            <a href="{% url 'pegasus_examples:pricing_page' %}" class="pg-button-secondary">
              <span>View Pricing Page</span>
              <span class="icon">
                <i class="fa fa-angle-double-right"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="pg-text-centered my-2">
    ...more coming soon!
  </div>
{% endblock %}

templates/pegasus/examples/tasks.html
{% extends "pegasus/examples/examples_base.html" %}
{% load static %}
{% block app %}
<section class="app-card">
  <h3 class="pg-title">Tasks Example</h3>
  <p class="pg-subtitle">
    Support background, long-running, or scheduled tasks easily with Celery
  </p>
  <div class="content">
    <p>
      Most applications eventually need to perform tasks that take longer than a few seconds to complete,
      for example data imports/exports.
      If yours is one of these, you'll probably want to use
      <a href="http://www.celeryproject.org/">Celery</a> for the job to run in the background.
    </p>
    <p>
      This page is a complete example that creates tasks for a background Celery process
      and displays the progress below.
      It should provide a perfect example to build from.
    </p>
    <p>
      <strong>Kick off your first Celery task below!</strong>
    </p>
    <button class="pg-button-primary mb-2" id="task-starter">
      <span>Run Task</span>
      <span class="icon">
        <i class="fa fa-angle-double-right"></i>
      </span>
    </button>
    <div class="progress-bar-demo">
      <div class='progress-wrapper'>
        <div id="progress-bar" class='progress-bar'>&nbsp;</div>
      </div>
      <div id="progress-bar-message">Waiting for progress to start...</div>
    </div>
    <p>
      For more information about how this works see:
      <a href="https://buildwithdjango.com/blog/post/celery-progress-bars/">
        Building Progress Bars for the Web with Django and Celery
      </a>
    </p>
  </div>
</section>
{% endblock %}
{% block page_js %}
    <script src="{% static 'celery_progress/celery_progress.js' %}"></script>
    <script src="{% static 'js/app-bundle.js' %}"></script>
    <script>
    const App = SiteJS.app;
    const apiUrl = "{% url 'pegasus_examples:tasks_api' %}";
    const progressUrl = "{% url 'celery_progress:task_status' 'task-id-stub' %}";
    document.addEventListener("DOMContentLoaded", function () {
        var trigger = document.getElementById('task-starter');
        trigger.addEventListener('click', function (e) {
            e.preventDefault();
            var pb = document.getElementById('progress-bar');
            pb.style.display = 'inherit';
            fetch(apiUrl, {
                method: 'post',
                credentials: 'same-origin',
                headers: {
                  'X-CSRFToken': App.Cookies.get('csrftoken'),
                }
            }).then(
                function (response) {
                    return response.text();
                }).then(function (text) {
                    var taskUrl = progressUrl.replace('task-id-stub', text);
                    CeleryProgressBar.initProgressBar(taskUrl, {
                        onProgress: function (progressBarElement, progressBarMessageElement, progress) {
                            progressBarElement.style.width = progress.percent + "%";
                            progressBarMessageElement.innerHTML = progress.current + ' of ' + progress.total + ' processed.';
                        },
                    });
                  })
                  .catch(function (error) {
                    console.error('Request failed', error);
                });
                e.preventDefault();
        }, false);
    });
    </script>
{% endblock %}